version: "2"
services:
    src:
        build: .
        ports: 
            - "8003:80"
        volumes:
            - ./src:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.4
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: myDatabase
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./database:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--mysql-native-password=ON']
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links: 
            - db:db
        ports:
            - 8002:80
        environment:
            MYSQL_ROOT_PASSWORD: admin
volumes:
    persistent:
